checksumBehavior: ignore

httpsProxy: http://127.0.0.1:7890

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: scripts/bootstrap.cjs
  - path: scripts/pod-install.cjs

yarnPath: .yarn/releases/yarn-4.0.1.cjs
