import { RTM_CHANNEL_TYPE } from '../AgoraRtmBase';
import { IRtmStorage, MetadataOptions, RtmMetadata } from '../IAgoraRtmStorage';
import { callIrisApi } from '../index';

/// Generated by terra, DO NOT MODIFY BY HAND.

// @ts-ignore
export class IRtmStorageImpl implements IRtmStorage {
  createMetadata(): RtmMetadata {
    const apiType = this.getApiTypeFromCreateMetadata();
    const jsonParams = {};
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.result;
  }

  protected getApiTypeFromCreateMetadata(): string {
    return 'RtmStorage_createMetadata';
  }

  setChannelMetadata(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    data: RtmMetadata,
    options: MetadataOptions,
    lockName: string,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromSetChannelMetadata();
    const jsonParams = {
      channelName: channelName,
      channelType: channelType,
      data: data,
      options: options,
      lockName: lockName,
      requestId: requestId,
      toJSON: () => {
        return {
          channelName: channelName,
          channelType: channelType,
          data: data,
          options: options,
          lockName: lockName,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromSetChannelMetadata(): string {
    return 'RtmStorage_setChannelMetadata';
  }

  updateChannelMetadata(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    data: RtmMetadata,
    options: MetadataOptions,
    lockName: string,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromUpdateChannelMetadata();
    const jsonParams = {
      channelName: channelName,
      channelType: channelType,
      data: data,
      options: options,
      lockName: lockName,
      requestId: requestId,
      toJSON: () => {
        return {
          channelName: channelName,
          channelType: channelType,
          data: data,
          options: options,
          lockName: lockName,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromUpdateChannelMetadata(): string {
    return 'RtmStorage_updateChannelMetadata';
  }

  removeChannelMetadata(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    data: RtmMetadata,
    options: MetadataOptions,
    lockName: string,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromRemoveChannelMetadata();
    const jsonParams = {
      channelName: channelName,
      channelType: channelType,
      data: data,
      options: options,
      lockName: lockName,
      requestId: requestId,
      toJSON: () => {
        return {
          channelName: channelName,
          channelType: channelType,
          data: data,
          options: options,
          lockName: lockName,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromRemoveChannelMetadata(): string {
    return 'RtmStorage_removeChannelMetadata';
  }

  getChannelMetadata(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromGetChannelMetadata();
    const jsonParams = {
      channelName: channelName,
      channelType: channelType,
      requestId: requestId,
      toJSON: () => {
        return {
          channelName: channelName,
          channelType: channelType,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromGetChannelMetadata(): string {
    return 'RtmStorage_getChannelMetadata';
  }

  setUserMetadata(
    userId: string,
    data: RtmMetadata,
    options: MetadataOptions,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromSetUserMetadata();
    const jsonParams = {
      userId: userId,
      data: data,
      options: options,
      requestId: requestId,
      toJSON: () => {
        return {
          userId: userId,
          data: data,
          options: options,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromSetUserMetadata(): string {
    return 'RtmStorage_setUserMetadata';
  }

  updateUserMetadata(
    userId: string,
    data: RtmMetadata,
    options: MetadataOptions,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromUpdateUserMetadata();
    const jsonParams = {
      userId: userId,
      data: data,
      options: options,
      requestId: requestId,
      toJSON: () => {
        return {
          userId: userId,
          data: data,
          options: options,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromUpdateUserMetadata(): string {
    return 'RtmStorage_updateUserMetadata';
  }

  removeUserMetadata(
    userId: string,
    data: RtmMetadata,
    options: MetadataOptions,
    requestId?: number
  ): number {
    const apiType = this.getApiTypeFromRemoveUserMetadata();
    const jsonParams = {
      userId: userId,
      data: data,
      options: options,
      requestId: requestId,
      toJSON: () => {
        return {
          userId: userId,
          data: data,
          options: options,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromRemoveUserMetadata(): string {
    return 'RtmStorage_removeUserMetadata';
  }

  getUserMetadata(userId: string, requestId?: number): number {
    const apiType = this.getApiTypeFromGetUserMetadata();
    const jsonParams = {
      userId: userId,
      requestId: requestId,
      toJSON: () => {
        return {
          userId: userId,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromGetUserMetadata(): string {
    return 'RtmStorage_getUserMetadata';
  }

  subscribeUserMetadata(userId: string, requestId?: number): number {
    const apiType = this.getApiTypeFromSubscribeUserMetadata();
    const jsonParams = {
      userId: userId,
      requestId: requestId,
      toJSON: () => {
        return {
          userId: userId,
          requestId: requestId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.requestId;
  }

  protected getApiTypeFromSubscribeUserMetadata(): string {
    return 'RtmStorage_subscribeUserMetadata';
  }

  unsubscribeUserMetadata(userId: string): number {
    const apiType = this.getApiTypeFromUnsubscribeUserMetadata();
    const jsonParams = {
      userId: userId,
      toJSON: () => {
        return {
          userId: userId,
        };
      },
    };
    const jsonResults = callIrisApi.call(this, apiType, jsonParams);
    return jsonResults.result;
  }

  protected getApiTypeFromUnsubscribeUserMetadata(): string {
    return 'RtmStorage_unsubscribeUserMetadata';
  }
}
