import { RTM_CHANNEL_TYPE } from './AgoraRtmBase';

/// Generated by terra, DO NOT MODIFY BY HAND.

/**
 * The IRtmLock class.
 *
 * This class provides the rtm lock methods that can be invoked by your app.
 */
export abstract class IRtmLock {
  abstract setLock(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    lockName: string,
    ttl: number,
    requestId?: number
  ): number;
  abstract getLocks(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    requestId?: number
  ): number;
  abstract removeLock(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    lockName: string,
    requestId?: number
  ): number;
  abstract acquireLock(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    lockName: string,
    retry: boolean,
    requestId?: number
  ): number;
  abstract releaseLock(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    lockName: string,
    requestId?: number
  ): number;
  abstract revokeLock(
    channelName: string,
    channelType: RTM_CHANNEL_TYPE,
    lockName: string,
    owner: string,
    requestId?: number
  ): number;
}
